version: "3.9"
services:
  mosquitto_sub:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto_sub
    depends_on:
      - alarmconcentrator
    command: mosquitto_sub -h mosquitto -p 1883 -t "topic/alarmConcentrator" -v
    restart: unless-stopped
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
  alarmConcentrator:
    image: byroncollins/alarmconcentrator:2.0.2
    ports:
      - "8080:8080"
    environment:
      - BROKER=tcp://alarmconcentrator-mosquitto-1:1883
      - PORT=8080
    depends_on:
      - mosquitto
    command: [ "/app/main" ]
